spring:
  application:
    name: support-ticket-backend
  profiles:
    active: dev
  datasource:
    url: jdbc:mysql://localhost:3306/ticket_v1?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Colombo
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 1234
  jackson:
    default-property-inclusion: non_null
  jpa:
    hibernate:
     ddl-auto: none
    properties:
      hibernate:
        format_sql: true
    show-sql: false
server:
  port: 8080

app:
  crypto:
    enabled: false
    excluded-paths: /actuator/**,/api/v1/health/status,/h2-console/**
    secret-key: ${APP_CRYPTO_SECRET_KEY:12345678901234567890123456789012}
    jwt:
      access-token-expiration-minutes: 30
      refresh-token-expiration-minutes: 1440
      secret: ${APP_JWT_SECRET:change-this-secret-value-in-production-minimum-32-chars}

logging:
  config: classpath:log4j2-spring.xml
